# Feburary 3 2025

---

# Placement Interview 

Set of **multiple choice** questions 
**3** Coding Problems

## MySQL Workbench

[MySQL Script](02_03.sql)

CMD connection:
- `mysql -u root -p [port] -h localhost`

**Dotenv** to protect the env file
`pip install python-dotenv` 

Create that .env folder following:
`MY_ENV_VAR="This is my env var content."`

Then on a script we import:
```python
import os
from dotenv import load_dotenv
```

Then we load our env and retrieve the key:
```python
load_dotenv()

MY_ENV_VAR = os.getenv('MY_ENV_VAR')
```

---

# MySQL Syntax 

**Comments** 
```mysql

# Providing single line comment like python 

/*

Multiple line comment 

*/

```

**Multiple statements on one line** 

```mysql
# Create a database and use it 
create database demo; use demo;
```

---

```mysql
/*
    DDL - Data Defintion: (Create, Alter, Drop) --> Affecting the Structure 
        - Idea of working with the table  
    DML - Data Manipulation: (Insert, Update, Delete) --> Affecting the Data 
        - Idea of working with the data
            DQL - Data Query (Select)
    DCL - Data Control 
    TCL - Perform a rollback state 
*/
```

---

**Table Level** 

Varchar(Doesn't need to be exact) but Char is **Fixed** letter

For Numbers:
- Int, Float(total_num_digits, decimal point), Double(total_num_digits, decimal point)

```mysql

create table t0(
    c1 int, 
    c2 char(10),
    c3 float
);

```

We could **DDL* to alter the table and modify a column 
`alter table table_name modify column column_name new_data_type` 
`alter table table_name rename column column_name new_column_name`

```mysql

show tables;

# DDL
alter table t0
modify column c2 varchar(11);

alter table t0 rename column c2 to c3;

alter table t0 add c2 char(10);

# DQL 
select * from t0;
```

---

# Primary key 

used to join two database 

```mysql
# Indexing behind the scenes 
create table Student(
    id int primary key,
    # Cannot be emptied
    fullName varchar(20) not null,
    # Must be a new entry (no duplicates)
    phone char(11) unique
)
```


## Constraints 

*not null*, *unique* --> Cannot be empty, Cannot be duplicated 

--- 

#  Dropping Tables 
`drop table table_name`

---

# DML (Data Manipulation) 

We look at insert, update and delete.


**Insert**
- `insert into table_name values (col1,col2,col3...)`
- `insert into table_name(col_name,col2_name,col6_name) values (col_val,col2_val,col6_val)`

**Quick DQL** 
- `select * from table` -> displays all content 
- `select col2,col1 from table`

**Delete (Remember the WHERE condition)**
- `delete from Course where condition`
- `delete from Course`  -> Deletes everything (Can't in safe mode)
- `set sql_safe_updates = 0`    -> Sets safe updates off 

**Update (Remember the WHERE condition)**
- `update Table set column = 'New Value' where condition`

```mysql 

create table Course(
    id int,
    name varchar(20) not null
);

# Insert 
insert into Course
values (1, "Python");

insert into Course(name, id)
values('Machine Learning', 1);

# DQL 
select name,id from Course;

# Deleting 
delete from Course
where id = 1;

# We just need to change id to primary key (for delete) instead of running safe mode OFF
alter table Course modify column id int primary key;

# Updating 

update Course set name = 'Javascript' where id = 2;
```

---

# DCL (Data Control Language) 

Control how users access database
`create user 'username'@'host' identified by 'password'`

Now instead of using `root` user we use `test` user with that set password 
- Set up a new connect if we wanted 
- `set password for `test`@`localhost` = 'new_password'`
- `alter user `test`@`localhost` identified  by 'new_password';`

Drop the user 
`drop user `test`@`localhost`;

Granting access to table 
`grant all on database.table to 'test'@'localhost';`

Revoke access to table 
`revoke all privileges, grant option from 'test'@'localhost';`

Granting Specific access not all 
`grant select,insert on database.table to 'test'@'localhost'`

```mysql 
# user_name@host 
create user 'test'@'localhost' identified by 'password';

# Changing user 
alter user `test`@`localhost` identified  by 'new_password';
set password for `test`@`localhost` = 'new_password';

# Dropping user 
drop user 'test'@'localhost';

# Granting access
grant all on database.table to 'test'@'localhost';

# Revoke 
revoke all privileges, grant option from 'test'@'localhost';

# Granting Specifis 
grant select,insert on database.table to 'test'@'localhost';

# See users
select user from mysql.user;
``` 

---

# Auto-Increment 

```mysql

create table AutoIncrementCourse(
    id int primary key auto_increment,
    name varchar(20) not null
)

```

---

# TCL (Transaction Control) 

Rollback to a state where it's working (Testing or Process)

Start a transction (checkpoint)
Then we could rollback to that state 

if we `savepoint transaction_save_name` we could `rollback to transaction_save_name`

`rollback` will go straight to **start transaction** 
- If you have a **savepoint** and then **rollback** passed that savepoint, that savepoint no longer exists
- 



```mysql
start transaction;
select * from Course;
update Course set name = 'Generative AI' where id= 2;
# You'll see the new update
select * from Course;
# Ignore everything in the middle and rollback to transaction state `
rollback;

# We could save transtions 
start transaction;
select * from Course;
update Course set name = 'Generative AI' where id= 2;
select * from Course; 
savepoint transaction_save_name1;
update Course set name = 'Generative AI 2' where id= 2;
select * from Course; 
rollback to transaction_save_name1;
# Commit to end the transaction
commit;
```

# MySQL - Python Connection

`pip install mysql-connector-python`

Connect to mysql 
- `con = mysql.connector.connect(host='localhost', user='root', password='pass', database='db')`

Set up the cursor to catch results 
-  `cursor = conn.cursor()`

Executing queries 
- `cursor.execute(query_statement)`

Grabbing result from row
- `result = [output for output in cursor.fetchall()]`

In [8]:
import mysql.connector
import os 
import dotenv

# All our ENV variables
dotenv.load_dotenv()

# Creating the connection 
try:
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password=os.getenv('MYSQL_PASSWORD'),
        database='tekbasic_training'
    )
    
    if conn.is_connected():
        print('Connected to MySQL database')
        # Based on this cursor we can execute any MySQL commands
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM autoincrementcourse')
        
        # Object with different rows (fetchall())
        # result = cursor.fetchall()
        # for row in result:
        #     print(row)
        result = "\n".join([str(output) for output in cursor.fetchall()])
        print(result)
        
except mysql.connector.Error as err:
    print(err)
else:
    # If our connection is good let's close for now
    conn.close()
    # Turn off cursor 
    cursor.close()
    print('Disconnecting')

Connected to MySQL database
(1, 'Python')
(2, 'Generative AI 3')
(3, 'Machine Learning')
Disconnecting

# Python OS 

---

```python
import os 

os.system('echo "Hello from shell OS"')
env_vars = os.environ 

env_vars.get('var_name')
```

---

What's nice is that you could have a space for multiple values for instance:
`MYSQL_CONN="LOCALHOST PASSWORD ROOT"`

Then we could `split(' ')` via spaces and use it that way

In [9]:
import os 
import dotenv

# All our ENV variables
dotenv.load_dotenv()

con_details = os.getenv('MYSQL_CONN').split(' ')
print(con_details)
print(os.getcwd())
# Lists all directories within current working directory 
print(os.listdir('.'))
# Checking a specific Directory 
print(os.listdir('C:\\Users\\Owwl\\PycharmProjects\\TekBasic'))

# We could make a folder  and remove it 
os.rmdir('Folder from Pycharm')
os.mkdir('Folder from Pycharm')
os.rmdir('Folder from Pycharm')
os.mkdir('Folder from Pycharm')
# os.rename('Folder from Pycharm', 'Folder From Pycharm')
print(os.listdir('.'))

['localhost', 'root', 'testing_password', 'tekbasic_training']
C:\Users\Owwl\PycharmProjects\TekBasic\02_Notes\02_03
['02_03_Notes.ipynb', '02_03_Notes.ipynb~']
['.env', '.git', '.gitignore', '.idea', '.venv', '01_Notes', '02_Notes', 'Review_Before_Exam', 'zoom_info.ipynb']

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Folder from Pycharm'

# Python File Handling

In [22]:
# with open('data.txt') as file:
#     print(file.read())

# But actually we write it with try/except block as well
# try:
#     file = open('data.txt')
#     print(file.read())
# except Exception as e:
#     print(e)

with open('data.txt', 'w') as file:
    file.write('Hello World')

with open('data.txt', 'a') as file:
    file.write('\nWe appened This as well Instead of overwritting')
    
# Reading 
with open('data.txt', 'r') as file:
    # We don't actually need to read 
    # print(file.read())
    for line in file:
        print(line)
    
    # Or we read a certain amount of characters
    print(file.read(10))
    # Seek and just moving the pointer so if we seek 10 then file.read(num) will read AT THAT POINT
    file.seek(0)
        
# Seek is good to reset 
with open('data.txt', 'r') as file:
    content = ''
    letter_code = [0, 5, 3]
    for code in letter_code:
        file.seek(code)
        content+=file.read(1)
    print(content)

Hello World

We appened This as well Instead of overwritting

H l